#ifndef MAIN_WINDOW_H
#define MAIN_WINDOW_H

#include <QMainWindow>
#include <QTimer>
#include <QtWidgets/QLabel>
// autogenerated by CMAKE_AUTOUIC
#include "ui_main_window.h"

// base class must be public
class MainWindow : public QMainWindow
{
public:
    MainWindow(QWidget *parent = NULL);

private:
    void pushed(bool checked);

    void timeout();

private:
    Ui::MainWindow ui;
    int counter;
    QTimer timer;
};

#endif // MAIN_WINDOW_H
